### Make a DataFrame of Hadith narrators (Narrator, Hadith_Count). Find the top 5 narrators with the most hadiths.

In [3]:
import requests
import pandas as pd

In [35]:
narrators = requests.get("https://hadithapi.com/public/api/hadiths?apiKey=$2y$10$uUXLSww3EbKebq1cljtoOuXYgwhabHvoXBewf410XDyhDuqXQj1su").json()["hadiths"]["data"]
fetch = [f"{i['englishNarrator']}" for i in narrators]
df = pd.DataFrame(fetch, columns=["Narrator"])
df

                                             Narrator
0   Narrated 'Umar bin Al-Khattab (May Allah be pl...
1   Narrated 'Aisha (the mother of the faithful be...
2                                    Narrated 'Aisha:
3   Narrated Jabir bin 'Abdullah Al-Ansari (while ...
4                           Narrated Said bin Jubair:
5                                Narrated Ibn 'Abbas:
6                      Narrated 'Abdullah bin 'Abbas:
7                                 Narrated Ibn 'Umar:
8                               Narrated Abu Huraira:
9                        Narrated 'Abdullah bin 'Amr:
10                                 Narrated Abu Musa:
11                       Narrated 'Abdullah bin 'Amr:
12                                     Narrated Anas:
13                              Narrated Abu Huraira:
14                                     Narrated Anas:
15                                     Narrated Anas:
16                                     Narrated Anas:
17                      Narrated 'Ubada bin As-Samit:
18                       Narrated Abu Said Al-Khudri:
19                                   Narrated 'Aisha:
20                                     Narrated Anas:
21                       Narrated Abu Said Al-Khudri:
22                       Narrated Abu Said Al-Khudri:
23                    Narrated 'Abdullah (bin 'Umar):
24                                Narrated Ibn 'Umar:

In [46]:
narrator_count = df.groupby("Narrator").size().reset_index(name="Hadith_Count")
top5 = narrator_count.sort_values(by="Hadith_Count", ascending=False).head(5)

print(top5)

                        Narrator  Hadith_Count
10                Narrated Anas:             5
9   Narrated Abu Said Al-Khudri:             3
2   Narrated 'Abdullah bin 'Amr:             2
12           Narrated Ibn 'Umar:             2
7          Narrated Abu Huraira:             2